-- Crear la tabla jugadores
create table public.jugadores (
  id bigint generated by default as identity primary key,
  nombre text not null
);

-- Insertar un registro de ejemplo
insert into public.jugadores (nombre) values ('Juan Pérez'); 